sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
    texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-bibtex-extra
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo apt install openjdk-8-jdk
script:
  - cd thesis
  - pdflatex -interaction=nonstopmode -halt-on-error thesis.tex
  - bibtex thesis || true
  - pdflatex -interaction=nonstopmode -halt-on-error thesis.tex
  - pdflatex -interaction=nonstopmode -halt-on-error thesis.tex
  - cd ../ui
  - npm i && npm run test:ci && npm run release
  - cd ..
notifications:
  email:
    on_success: never
deploy:
  - provider: releases
    api_key:
      secure: q35rnX2Oh9suzzBTo45TE7xuRKml5PRTCsCn+mF+i6tgOPL/kW85gs1PsHatCni2DDTD+mAzgIDAlgK3kl3EOZ5CfByekyQNLTagF3MD4lBV1uMVvuaA0A6Q0WQi+VTvpVXoSXw/hsw4VdQpX8wqgPx40tm10dm7VkNPshlkA0S3D3AIJruSjmqs1pyJWlORXCGgGU1bLULTa2/NhF0G/AGlITWAufV6NWcGHjbRQ8jNY5nyK5FkTm5mihs8KxPpylVnCMX4H5E0XPOYWrLZyn3kywGP7NSfxQjQ2OswdTsG3gMmX5hIfncsqKOke+Wdzw5eHPPIs6tmt487b2m91n7FtXTwRpslVxaSer5JowqXHYZ90TZYMxLwKxtq2fVP3fb9mDvoBh+S44AyxpGRgAprL4SiEHkqaC7Y0g/1uOCa2UZUZ6DYqKeu0bosOugkwqEkfo24tcO6JyoiW/iOQJAznH0ILwnM4mec840pzMetFh2dW0OG55uQmmRGJVHgA+wCZ/Py7z0JBDELNKx6gZPoMC1IgIUs7Sc5qN3coi15lH8RqPwpcLFAGgTExaJnxk5Ji3S/uDTWeVtp8S9jKGPn6JEGi4yukPs/9ol5K/92QRo2KZ88lf/dqjrU0GeF9RRvxt/fLJWJo5kcT7mUkXu9QyLmg8qdghnR7gG49E0=
    file: thesis/thesis.pdf
    skip_cleanup: true
    on:
      repo: jerben/linked-data-driven-ui
  - provider: s3
    access_key_id: AKIAIPWMNPYQY7LBRZ2Q
    secret_access_key:
      secure: QIT4mKb7O6ZfPOnk+3iKastJJzlRij2JJbrRLO5EohGKvHUZTRh2aupcZkIIx6D58qFIl8c08Y9C/t6XFo0Pp61lfjdDX4wAFpDeMXjXgGVx8Fx24WNfo00hcuW53JP/xT8PfWt7VNypQ1UUyja0nuSPGxX2xXGsrP4aKgOLqf5JWAaofbTQUwGNB4XLuZb881BRNYmpUCKa7uF9BdAaCuDXDUhopa4UHrcWi6UFYVf1iYi7H0RRGfTjC3NdX/FcPnlNDLCzA7cL7tLjanBaO2oIkDLtN3W8oHtOialOjIZgfivfcoP1Q1hjeyK5v3QYjdEkBxzKnmiJECNJFnfs+LC8b+uhHFteYqhLMbzwSnAOdTGuOEAcA4PdkuBlHVGYv/0gfd9upXVpOm/vRlvvTASOsBEj1xYuLsQcSK8LUoULkruAdD0kvyGL44tacU3qNJZaI/7/xLQcb/cj3AhqwdjmRsVhD6UEcHSdqzYLkf6aeJ+6SBHqPJA7igUeKCY5wMklZ7ysP36PrBROtAYFkmjzSqw8lWkCsp2qzGLWjQyU19p9da+Um7j5T6c21dm7HIeCX9nxpYa0WPsKc2J8rHLiV7Xyz89+qhfb9UkZmKx8Sr+GeVGATNF/YrIj/dLw85pcle1vVjl5iINS6Qaa/guy2yWiNPL8Wu4TCtixzfk=
    bucket: lddui.erben.sh
    local-dir: ui/public
    skip_cleanup: true
    region: eu-central-1
    acl: public_read
    on:
      repo: jerben/linked-data-driven-ui
