language: node_js
node_js:
  - "8"
script:
  - yarn --cwd client install
  - yarn --cwd client install
  - yarn --cwd api install
  - yarn --cwd api build
notifications:
  email:
    on_success: never
